# Generated by Django 3.2.16 on 2023-02-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20230220_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='credit',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
