# Generated by Django 3.2.16 on 2023-02-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='durée',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
